version: '3.8'

services:
  demos_django:
    image: 'demos_django:latest'
    build:
      context: .
      dockerfile: Dockerfile
      # args:
        # options: --reload
    container_name: demos_django
    restart: always
    volumes:
      - ./src:/usr/src/app
      - ./src/static:/static      
    ports:
      - 8001:8000
    env_file:
      - ./.env
    depends_on:
      - demos_pgdb  

  demos_nginx:
    image: 'demos_nginx:latest'
    build:
      context: .
      dockerfile: Dockerfile_nginx      
    container_name: demos_nginx
    restart: always
    ports:
      - 8002:80 
    volumes: 
      - ./src:/usr/src/app  
      - ./src/static:/static
    depends_on:
      - demos_django  

  demos_pgdb:
    image: 'demos_pgdb:latest'
    build:
      context: .
      dockerfile: Dockerfile_postgres
    container_name: demos_pgdb
    restart: always
    env_file:
      - ./.env     
    ports:
      - 5433:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

  demos_frontend:
    image: 'demos_frontend:latest'
    build: 
      context: .
      dockerfile: Dockerfile_angular
    container_name: demos_frontend 
    restart: always
    mem_limit: 512m
    mem_reservation: 128M
    cpus: 0.5
    ports:
      - 4201:80
    volumes:
      - ./front_end:/usr/local/demos_frontend/

volumes:
  postgres_data:

